<?php

/*
 * Content for the footer. Set to false to hide the footer.
 * Default: 'Changelog generated by <a href="'.$Fascel['constants']['homepage'].'">Fascel</a> v'.$Fascel['constants']['version']
 */
$Fascel['config']['footer'] = 'Changelog generated by <a href="'.$Fascel['constants']['homepage'].'">Fascel</a> v'.$Fascel['constants']['version'];

?>