<?php

/*
 * Whether to connect to a database or not.
 * Set to true if you don't already initiate your own connection.
 * Default: false
 */
$Fascel['config']['connect_to_database'] = false;

/*
 * Content for the footer. Set to false to hide the footer.
 * Default: 'Changelog generated by <a href="'.$Fascel['constants']['homepage'].'">Fascel</a> v'.$Fascel['constants']['version']
 */
$Fascel['config']['footer'] = 'Changelog generated by <a href="'.$Fascel['constants']['homepage'].'">Fascel</a> v'.$Fascel['constants']['version'];

?>
